---
title: Topic
---

<div class="container" style="min-height:75vh;">

<h1>Topic</h1>

In recent years, R users’ understanding of Shiny has greatly increased but so have
client expectations. While one of Shiny’s greatest strengths is that it allows producing
web applications solely from R code, meeting client’s more delicate expectations will
often involve going beyond R code and work with HTML, CSS, and JavaScript.
We recognize that R developers tend not to be familiar with the latter as they
generally do not have significant background in web development, these may
therefore appear daunting at first.

This workshop aims to put attendees at ease with inviting those web technologies
into their shiny applications so they can exceed client’s expectations. The workshop
will comprise three parts.

Part 1 hones in on the development of a new template on top of Shiny with the
{htmltools} package. Workshop attendees will have the opportunity to collaborate
with the RinteRface team on the {shinybulma} project
(https://github.com/RinteRface/shinybulma).

Part 2 delves into bi-directional communication in Shiny: how the R server
communicates with the front-end and vice versa, how the input/output system works.

Part 3 ends the workshop by exposing all the less known functions/methods that are
however likely to help you in your Shiny journey!

</div>
